name: Delivery
on:
  push:
    branches:
      - 'develop'
  pull_request:
    types:
      - opened
    branches:
      - 'main'
jobs:
  release:
    runs-on: ubuntu-20.04
    container:
      image: google/cloud-sdk:411.0.0-slim
    env:
      GOOGLE_APPLICATION_CREDENTIALS: key.json
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create GCP Import import.json
        env:
          IMPORT: ${{ secrets.GOOGLE_IMPORT_CREDENTIALS }}
        run: echo $IMPORT | base64 --decode > import.json
      - name: Test script
        env:
          PROJECT: ${{ secrets.WORKSPACE_PROJECT }}
        # Missing filters for environment values
        run: |
          gcloud compute images create \
          ssh-bounce-$(cat VERSION.txt | sed -E 's/^(.*)\.(.*)\.(.*)$/\1-\2-\3/')-$(echo $GITHUB_SHA | cut -c -10)-debian-11 \
          --source-image=ssh-bounce-$(cat VERSION.txt | sed -E 's/^(.*)\.(.*)\.(.*)$/\1-\2-\3/')-$($GITHUB_SHA | cut -c -10)-debian-11 \
          --family=ssh-bounce-debian-11 \
          --labels version=$(cat VERSION.txt | sed -E 's/^(.*)\.(.*)\.(.*)$/\1-\2-\3/'),version_type='release',commit=$GITHUBB_SHA \
          --source-image-project=$PROJECT \
          --project=coucou