name: Delivery
on:
  push:
    branches:
      - 'develop'
  pull_request:
    types:
      - opened
    branches:
      - 'main'
jobs:
  release:
    runs-on: ubuntu-20.04
    container:
      image: google/cloud-sdk:411.0.0-slim
    env:
      GOOGLE_APPLICATION_CREDENTIALS: key.json
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create GCP Import import.json
        env:
          IMPORT: ${{ secrets.GOOGLE_IMPORT_CREDENTIALS }}
        run: echo $IMPORT | base64 --decode > import.json
      - name: Build Packer image
        run: |
          gcloud compute images create \
          ${{ secrets.WORKSPACE.name }}-$(cat VERSION.txt | sed -E 's/^(.*)\.(.*)\.(.*)$/\1-\2-\3/')-$($GITHUB_SHA | cut -c -10)-${{ secrets.MACHINE.source_image_family }} \
          --source-image=${{ secrets.WORKSPACE.name }}-$(cat VERSION.txt | sed -E 's/^(.*)\.(.*)\.(.*)$/\1-\2-\3/')-$($GITHUB_SHA | cut -c -10)-${{ secrets.MACHINE.source_image_family }} \
          --family=${{ secrets.WORKSPACE.name}}-${{ secrets.MACHINE.source_image_family}} \
          --labels=[version=$(cat VERSION.txt | sed -E 's/^(.*)\.(.*)\.(.*)$/\1-\2-\3/'), version_type='release', commit=$GITHUBB_SHA] \
          --source-image-project=${{ secrets.WORKSPACE.project }} \
          --project=coucou