name: Delivery
on:
  pull_request:
    branches:
      - 'develop'
jobs:
  release:
    runs-on: ubuntu-20.04
    container:
      image: google/cloud-sdk:411.0.0-slim
    env:
      GOOGLE_APPLICATION_CREDENTIALS: key.json
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create GCP Import import.json
        env:
          IMPORT: ${{ secrets.GOOGLE_IMPORT_CREDENTIALS }}
        run: echo $IMPORT | base64 --decode > import.json
      - name: Test script
        env:
          PROJECT: ${{ secrets.WORKSPACE_PROJECT }}
        # Missing filters for environment values
        run: |
          gcloud auth activate-service-account 'workspace-workstation-v1@workspace-workstation-v1-7p6l.iam.gserviceaccount.com' --key-file=import.json;
          gcloud compute images create \
          bounce-$(cat VERSION.txt | sed -E 's/^(.*)\.(.*)\.(.*)$/\1-\2-\3/')-$(echo ${{ github.event.pull_request.head.sha }} | cut -c -10)-debian-11 \
          --source-image=bounce-$(cat VERSION.txt | sed -E 's/^(.*)\.(.*)\.(.*)$/\1-\2-\3/')-$(echo ${{ github.event.pull_request.head.sha }} | cut -c -10)-debian-11 \
          --family=bounce-debian-11 \
          --labels version=$(cat VERSION.txt | sed -E 's/^(.*)\.(.*)\.(.*)$/\1-\2-\3/'),version_type='release',commit=$GITHUB_SHA \
          --source-image-project=$PROJECT \
          --project=workspace-workstation-v1-7p6l