name: Lint
on:
 push:
jobs:
  packer:
    runs-on: ubuntu-20.04
    container:
      image: raphaeldegail/packer:1.8.0
    env:
      PKR_VAR_name: "aaa"
      PKR_VAR_project: "aaa"
      PKR_VAR_region: "aaa"
      PKR_VAR_rsa_key: "aaa"
      PKR_VAR_rsa_pub: "aaa"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check format of Packer script
        run: packer fmt -check bounce.pkr.hcl
      - name: Initialize packer with plugins
        run: packer init bounce.pkr.hcl 
      - name: Validate Packer script
        run: packer validate bounce.pkr.hcl